music = {
    # Hollywood songs
    "blinding lights": "https://www.youtube.com/watch?v=fHI8X4OXluQ",
    "shape of you": "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    "someone like you": "https://www.youtube.com/watch?v=hLQl3WQQoQ0",
    "senorita": "https://www.youtube.com/watch?v=Pkh8UtuejGw",
    "stay": "https://www.youtube.com/watch?v=kTJczUoc26U",
    "believer": "https://www.youtube.com/watch?v=7wtfhZwyrcc",
    "let me love you": "https://www.youtube.com/watch?v=7NOSDKb0HlU",
    "levitating": "https://www.youtube.com/watch?v=TUVcZfQe-Kw",
    "perfect": "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    "peaches": "https://www.youtube.com/watch?v=tQ0yjYUFKAE",
    "industry baby": "https://www.youtube.com/watch?v=UTHLKHL_whs",
    "happier": "https://www.youtube.com/watch?v=m7Bc3pLyij0",
    "counting stars": "https://www.youtube.com/watch?v=hT_nvWreIhg",
    "uptown funk": "https://www.youtube.com/watch?v=OPf0YbXqDm0",
    "thunder": "https://www.youtube.com/watch?v=fKopy74weus",
    "bad habits": "https://www.youtube.com/watch?v=orJSJGHjBLI",
    "memories": "https://www.youtube.com/watch?v=SlPhMPnQ58k",
    "as it was": "https://www.youtube.com/watch?v=H5v3kku4y6Q",
    "ghost": "https://www.youtube.com/watch?v=Fp8msa5uYsc",
    "attention": "https://www.youtube.com/watch?v=nfs8NYg7yQM",
    "cheap thrills": "https://www.youtube.com/watch?v=nYh-n7EOtMA",
    "love me like you do": "https://www.youtube.com/watch?v=AJtDXIazrMo",
    "closer": "https://www.youtube.com/watch?v=PT2_F-1esPk",
    "photograph": "https://www.youtube.com/watch?v=nSDgHBxUbVQ",
    "see you again": "https://www.youtube.com/watch?v=RgKAFK5djSk",
    "night changes": "https://www.youtube.com/watch?v=syFZfO_wfMQ",
    "lovely": "https://www.youtube.com/watch?v=V1Pl8CzNzCw",
    "something just like this": "https://www.youtube.com/watch?v=FM7MFYoylVs",
    "wrecking ball": "https://www.youtube.com/watch?v=My2FRPA3Gf8",
    "counting moments": "https://www.youtube.com/watch?v=2vjPBrBU-TM",
    "shivers": "https://www.youtube.com/watch?v=Il0S8BoucSA",
    "stitches": "https://www.youtube.com/watch?v=VbfpW0pbvaU",
    "bad guy": "https://www.youtube.com/watch?v=DyDfgMOUjCI",
    "watermelon sugar": "https://www.youtube.com/watch?v=E07s5ZYygMg",
    "girls like you": "https://www.youtube.com/watch?v=aJOTlE1K90k",
    "cold water": "https://www.youtube.com/watch?v=nBtDsQ4fhXY",
    "thunderclouds": "https://www.youtube.com/watch?v=kg1BljLu9YY",
    "i m yours": "https://www.youtube.com/watch?v=EkHTsc9PU2A",
    "counting blue cars": "https://www.youtube.com/watch?v=Clxtg2pFTQM",

    # Hindi songs
    "apna bana le": "https://www.youtube.com/watch?v=E0CZJvZzD7U",
    "kesariya": "https://www.youtube.com/watch?v=BddP6PYo2gs",
    "raataan lambiyan": "https://www.youtube.com/watch?v=gvyUuxdRdR4",
    "tum hi ho": "https://www.youtube.com/watch?v=Umqb9KENgmk",
    "tera ban jaunga": "https://www.youtube.com/watch?v=CHpHTUuU0jg",
    "shayad": "https://www.youtube.com/watch?v=YxWlaYCA8MU",
    "phir aur kya chahiye": "https://www.youtube.com/watch?v=1vU6a7NqUo8",
    "ranjha": "https://www.youtube.com/watch?v=7XK9izmG2Y8",
    "agar tum saath ho": "https://www.youtube.com/watch?v=sK7riqg2mr4",
    "galliyan": "https://www.youtube.com/watch?v=PL6xHeBqDEY",

    # Punjabi bangers
    "lamberghini": "https://www.youtube.com/watch?v=H0Zxpz1aY6M",
    "3 peg": "https://www.youtube.com/watch?v=U6t4cj3Jv4",
    "laung da lashkara": "https://www.youtube.com/watch?v=2z4po6t8cY8",
    "illegal weapon": "https://www.youtube.com/watch?v=V3r6X1b0pXg",
    "spain": "https://www.youtube.com/watch?v=c20XsM9BWEM",
    "admiring you": "https://www.youtube.com/watch?v=k85UB5bq6PU",
    "wavy": "https://www.youtube.com/watch?v=XTp5jRaUWs8&list=RDEMJj0weLcfSL_fmHFYgkc7UEQ&index=2",
    "52 bars": "https://www.youtube.com/watch?v=XTp5jRaUWs8&list=RDEMJj0weLcfSL_fmHFYgkc7UEQ&index=2",
    "excuses": "https://www.youtube.com/watch?v=Vx2C_D2BLUw&list=RDEMJj0weLcfSL_fmHFYgkc7UEQ&index=3",
    "winning speech": "https://www.youtube.com/watch?v=vsIxstUwDkI&list=RDEMJj0weLcfSL_fmHFYgkc7UEQ&index=3",
}